qcacld-3.0: Fix uninitialized variable
Clang warns:
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_wext.c:7185:6: error:
      variable 'sme_config' is used uninitialized whenever 'if' condition is
      false [-Werror,-Wsometimes-uninitialized]
        if (phymode != -EIO) {
            ^~~~~~~~~~~~~~~
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_wext.c:7263:6: note:
      uninitialized use occurs here
        if (sme_config)
            ^~~~~~~~~~
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_wext.c:7185:2: note:
      remove the 'if' if its condition is always true
        if (phymode != -EIO) {
        ^~~~~~~~~~~~~~~~~~~~~
drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_wext.c:6981:30: note:
      initialize the variable 'sme_config' to silence this warning
        tSmeConfigParams *sme_config;
                                    ^
                                     = NULL
1 error generated.